-- FieldTrack Admin Migration
-- NOTE: All admin functions are now included in supabase-migration.sql
-- Run supabase-migration.sql instead - it contains everything:
-- - All tables (core + HRMS + trips)
-- - All RLS policies (user + manager level)
-- - All admin RPC functions
-- - All triggers and defaults
-- - Email approval function (process_leave_from_email)
--
-- This file is kept for reference only.
-- Please run supabase-migration.sql in your Supabase SQL Editor.
